[options]
admin_passwd = $pbkdf2-sha512$600000$ohQixJhzDkFoDQFAyNk75w$bkdR6eEyQPJrAk8rCVrnN0fxSPqdI5bT96eP5ooxXWD.GBpUJoygHURBaTdoVQKwvVkQvy0OVN1js2YudcxE8A
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
log_level = info
limit_time_cpu = 600
limit_time_real = 1200

