re[options]
admin_passwd = admin123
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
log_level = info
limit_time_cpu = 600
limit_time_real = 1200

